version: '3'
services:
  mysql:
    image: mysql:latest
    tmpfs:
      - /var/lib/mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=golangdorset
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
volumes:
  mysql_data:
